package control;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.MultipartConfig;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.Part;
import model.product;
import service.Shop_Product_Handle;

import com.cloudinary.Cloudinary;
import com.cloudinary.utils.ObjectUtils;

import java.io.File;
import java.io.IOException;
import java.nio.file.Paths;
import java.util.Map;

@MultipartConfig(
    fileSizeThreshold = 1024 * 1024 * 2,
    maxFileSize = 1024 * 1024 * 5,
    maxRequestSize = 1024 * 1024 * 10
)
public class Add_Product extends HttpServlet {
    private static final long serialVersionUID = 1L;
    
    private Cloudinary cloudinary;
    
    @Override
    public void init() {
    	  cloudinary = new Cloudinary(ObjectUtils.asMap(
    		        "cloud_name", System.getenv("CLOUDINARY_CLOUD_NAME"),
    		        "api_key", System.getenv("CLOUDINARY_API_KEY"),
    		        "api_secret", System.getenv("CLOUDINARY_API_SECRET")
    		    ));
    }

    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        try {
            // ❌ PRODUCT ID REMOVED - Auto-generated by database
            // int productId = Integer.parseInt(request.getParameter("productId"));
            
            // ✅ ONLY THESE FIELDS FROM USER
            String productName = request.getParameter("productName");
            double productPrice = Double.parseDouble(request.getParameter("productPrice"));
            int productQty = Integer.parseInt(request.getParameter("productQty"));

            // Handle image file upload
            Part filePart = request.getPart("productImage");
            String fileName = Paths.get(filePart.getSubmittedFileName()).getFileName().toString();
            
            // Save to temp file
            String tempDir = System.getProperty("java.io.tmpdir");
            String tempFilePath = tempDir + File.separator + System.currentTimeMillis() + "_" + fileName;
            File tempFile = new File(tempFilePath);
            filePart.write(tempFilePath);
            
            // Upload to Cloudinary
            Map uploadResult = cloudinary.uploader().upload(
                tempFile,
                ObjectUtils.asMap(
                    "public_id", "products/" + System.currentTimeMillis() + "_" + fileName
                )
            );
            
            // Delete temp file
            tempFile.delete();
            
            // Get the Cloudinary URL
            String imageUrl = (String) uploadResult.get("secure_url");

            // Create product object - NO productId!
            product p = new product();
            // p.setProduct_Id(productId);  ← REMOVED!
            p.setProduct_Name(productName);
            p.setProduct_productPrice(productPrice);
            p.setProduct_Image(imageUrl);
            p.setProductQty(productQty);

            // Save to database
            Shop_Product_Handle sph = new Shop_Product_Handle();
            sph.Add_Product(p);
            
            response.sendRedirect("adminpannel.jsp?msg=added");
            
        } catch (Exception e) {
            e.printStackTrace();
            response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, 
                "Failed to add product: " + e.getMessage());
        }
    }
}